/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.QuanLyTaiKhoanNVDAO;
import Entity.NguoiDung;
import TienIchHoTro.Dialog;
import java.awt.Color;
import java.awt.LayoutManager;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author congc
 */
public class QuanlyTaiKhoanNV extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private List<NguoiDung> listND = new ArrayList<>();
    private DAO.QuanLyTaiKhoanNVDAO qlTKNV = new QuanLyTaiKhoanNVDAO();
    private Connection conn = null;

    /**
     * Creates new form QuanlyTaiKhoanNV
     */
    public QuanlyTaiKhoanNV() {
        initComponents();
        conn = TienIchHoTro.ConnectToSQL.getConnect();
        fillTable();
        ButtonGroup btnGrp = new ButtonGroup();
        btnGrp.add(rbn_GiangVien);
        btnGrp.add(rbn_KeToan);
        rbn_GiangVien.isSelected();
    }

    private void fillTable() {
        dtm = (DefaultTableModel) tbl_TKNhanVien.getModel();
        dtm.setRowCount(0);
        listND = qlTKNV.selectAll(conn);
        for (NguoiDung nd : listND) {
            Object[] row = new Object[]{
                nd.getMaNhanVien(),
                nd.getTenDangNhap(),
                nd.getMatKhau(),
                nd.getVaiTro() == 2 ? "Giảng viên" : nd.getVaiTro() == 1 ? "Kế toán" : " Quản lý"
            };
            dtm.addRow(row);
        }

    }

    private boolean nullTK() {
        Border border = BorderFactory.createLineBorder(Color.red);
        if (txt_TenDangNhap.getText().equals("") && txt_TenDangNhap.getText().isEmpty() && txt_MatKhau.getText().equals("") && txt_MatKhau.getText().isEmpty()) {
            LBL_LoiTenDangNhap.setText("Thiếu tên đăng nhập rồi nhập lại bạn nhé");
            lbl_LoiMK.setText("Thiếu mật khẩu rồi nhập lại bạn nhé");
            txt_MatKhau.setBorder(border);
            txt_TenDangNhap.setBorder(border);
            txt_TenDangNhap.requestFocus();
            return false;
        }

        if (txt_TenDangNhap.getText().equals("") && txt_TenDangNhap.getText().isEmpty()) {
            LBL_LoiTenDangNhap.setText("Thiếu tên đăng nhập rồi nhập lại bạn nhé");
            txt_TenDangNhap.setBorder(border);
            txt_TenDangNhap.requestFocus();
            return false;

        }
        if (txt_MatKhau.getText().equals("") && txt_MatKhau.getText().isEmpty()) {
            lbl_LoiMK.setText("Thiếu mật khẩu rồi nhập lại bạn nhé");
            txt_MatKhau.setBorder(border);
            txt_MatKhau.requestFocus();
            return false;
        }
        return true;
    }

    private boolean nullTimKiem() {
        Border border = BorderFactory.createLineBorder(Color.red);
        if (txt_TimKiem.getText().equals("") && txt_TimKiem.getText().isEmpty()) {
            txt_TimKiem.setText("Vui Lòng nhập đúng định dạng mã nhân viên");
            txt_TimKiem.setForeground(Color.red);
            txt_TimKiem.setBorder(border);
            txt_TimKiem.requestFocus();
            return false;
        }
        return true;
    }

    private boolean checkTrung() {
        for (NguoiDung nguoiDung : listND) {
            if (txt_TenDangNhap.getText().equals(nguoiDung.getTenDangNhap())) {
                LBL_LoiTenDangNhap.setText("Trùng tên đăng nhập rồi nhập lại bạn nhé!");
                txt_TenDangNhap.setBorder((Border) Color.red);
                txt_TenDangNhap.requestFocus();
                return false;
            }

        }
        return true;
    }

    private void clear() {
        txt_TenDangNhap.setText("");
        txt_MatKhau.setText("");
        rbn_GiangVien.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_TrangChu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_MatKhau = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbn_GiangVien = new javax.swing.JRadioButton();
        rbn_KeToan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_LoiMK = new javax.swing.JLabel();
        LBL_LoiTenDangNhap = new javax.swing.JLabel();
        txt_TenDangNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_TKNhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_SuaTaiKhoan = new javax.swing.JButton();
        btn_ThemTaiKhoan = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_XoaTaiKhoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btn_TrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Home.png"))); // NOI18N
        btn_TrangChu.setText("Trang chủ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quản lý tài khoản nhân viên");

        txt_TimKiem.setText("Nhập mã nhân viên");

        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Search.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên đăng nhập");

        txt_MatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mật khẩu");

        rbn_GiangVien.setText("Giảng Viên");

        rbn_KeToan.setText("Kế toán");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Vai trò");

        lbl_LoiMK.setBackground(new java.awt.Color(255, 255, 255));
        lbl_LoiMK.setForeground(new java.awt.Color(255, 0, 0));

        LBL_LoiTenDangNhap.setForeground(new java.awt.Color(255, 0, 0));

        txt_TenDangNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MatKhau)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbn_GiangVien)
                        .addGap(32, 32, 32)
                        .addComponent(rbn_KeToan))
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_LoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LBL_LoiTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txt_TenDangNhap)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_LoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn_GiangVien)
                    .addComponent(rbn_KeToan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(LBL_LoiTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(176, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(txt_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );

        tbl_TKNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên đăng nhập", "Mật khẩu", "Vai trò"
            }
        ));
        tbl_TKNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TKNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_TKNhanVien);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btn_SuaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Edit.png"))); // NOI18N
        btn_SuaTaiKhoan.setText("Sửa tài khoản");
        btn_SuaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaTaiKhoanActionPerformed(evt);
            }
        });

        btn_ThemTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Add.png"))); // NOI18N
        btn_ThemTaiKhoan.setText("Thêm tài khoản");
        btn_ThemTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemTaiKhoanActionPerformed(evt);
            }
        });

        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Refresh.png"))); // NOI18N
        btn_Clear.setText("Clear ");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_XoaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Delete.png"))); // NOI18N
        btn_XoaTaiKhoan.setText("Xóa tài khoản");
        btn_XoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ThemTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_SuaTaiKhoan)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SuaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_TrangChu)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed

        try {
            if (nullTimKiem()) {
                Border border = BorderFactory.createLineBorder(Color.black);
                txt_TimKiem.setBorder(border);
                List<NguoiDung> listND = qlTKNV.search(Integer.parseInt(txt_TimKiem.getText()), conn);
                dtm.setRowCount(0);
                for (NguoiDung nd : listND) {
                    Vector<Object> vec = new Vector<>();
                    vec.add(nd.getMaNhanVien());
                    vec.add(nd.getTenDangNhap());
                    vec.add(nd.getMatKhau());
                    vec.add(nd.getVaiTro());
                    dtm.addRow(vec);
                }
            }
        } catch (Exception e) {
            Dialog.alert(this, "Mã nhân viên không tồn tại"+e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void tbl_TKNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TKNhanVienMouseClicked

        int vitri = tbl_TKNhanVien.getSelectedRow();
        if (vitri >= 0) {
            Integer row = (Integer) tbl_TKNhanVien.getValueAt(vitri, 0);
            NguoiDung nd = qlTKNV.fromTableToText(row, conn);
            if (nd != null) {
                txt_TenDangNhap.setText(nd.getTenDangNhap());
                txt_MatKhau.setText(nd.getMatKhau());
                if (nd.getVaiTro() == 2) {
                    rbn_GiangVien.setSelected(true);
                }
                if (nd.getVaiTro() == 1) {
                    rbn_KeToan.setSelected(true);
                }
            }
        }

    }//GEN-LAST:event_tbl_TKNhanVienMouseClicked

    private void btn_SuaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaTaiKhoanActionPerformed

        try {
            if (nullTK()) {
                if (checkTrung()) {
                    NguoiDung nd = new NguoiDung();
                    txt_TenDangNhap.setText(nd.getTenDangNhap());
                    txt_MatKhau.setText(nd.getMatKhau());
                    int vaitro = 0;
                    if (nd.getVaiTro() == 2) {
                        rbn_GiangVien.isSelected();
                    }
                    if (nd.getVaiTro() == 1) {
                        rbn_KeToan.isSelected();
                    }
                    qlTKNV.update(nd, conn);
                    fillTable();
                    clear();
                    Dialog.alert(this, "Sửa thành công");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            Dialog.alert(this, "Sửa không thành công"+ " "+e.getMessage());
        }

    }//GEN-LAST:event_btn_SuaTaiKhoanActionPerformed

    private void btn_ThemTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemTaiKhoanActionPerformed

        try {
            if (nullTK()) {
                if (checkTrung()) {
                    Border border = BorderFactory.createLineBorder(Color.black);
                    txt_TenDangNhap.setBorder(border);
                    txt_MatKhau.setBorder(border);
                    NguoiDung nd = new NguoiDung();
                    nd.setTenDangNhap(txt_TenDangNhap.getText());
                    nd.setMatKhau(txt_MatKhau.getText());
                    int vaitroNV = 0;
                    if (rbn_GiangVien.isSelected()) {
                        vaitroNV = 2;
                    }
                    if (rbn_KeToan.isSelected()) {
                        vaitroNV = 1;
                    }
                    nd.setVaiTro(vaitroNV);
                    boolean insertTK = qlTKNV.insert(nd, conn);
                    fillTable();
                    clear();
                    TienIchHoTro.Dialog.alert(this, "Thêm thành công");
                    return;
                }
            }
        } catch (Exception e) {
            Dialog.alert(this, "Thêm thất bại !"+ " "+e.getMessage());
            e.printStackTrace();
            return;
        }


    }//GEN-LAST:event_btn_ThemTaiKhoanActionPerformed

    private void btn_XoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTaiKhoanActionPerformed
        try {
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tài khoản này", "Xóa tài khoản nhân viên", JOptionPane.YES_NO_OPTION);
            if (hoi == JOptionPane.YES_OPTION) {
                int vitri = tbl_TKNhanVien.getSelectedRow();

                if (vitri >= 0) {
                    Integer row = (Integer) tbl_TKNhanVien.getValueAt(vitri, 0);
                    NguoiDung nd = qlTKNV.delete(row, conn);
                    fillTable();
                    clear();
                }
                Dialog.alert(this, "xóa thành công");
            } else {
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            Dialog.alert(this, "xóa không thành công" + " "+e.getMessage());
        }


    }//GEN-LAST:event_btn_XoaTaiKhoanActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        Border border = BorderFactory.createLineBorder(Color.BLACK);
        txt_TenDangNhap.setText("");
        txt_TenDangNhap.setBorder(border);
        txt_MatKhau.setText("");
        txt_MatKhau.setBorder(border);
        LBL_LoiTenDangNhap.setText("");
        lbl_LoiMK.setText("");
        txt_TimKiem.setBorder(border);
        txt_TimKiem.setText("Nhập mã nhân viên");
        txt_TimKiem.setForeground(Color.black);
    }//GEN-LAST:event_btn_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanlyTaiKhoanNV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanlyTaiKhoanNV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanlyTaiKhoanNV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlyTaiKhoanNV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanlyTaiKhoanNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_LoiTenDangNhap;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_SuaTaiKhoan;
    private javax.swing.JButton btn_ThemTaiKhoan;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_TrangChu;
    private javax.swing.JButton btn_XoaTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_LoiMK;
    private javax.swing.JRadioButton rbn_GiangVien;
    private javax.swing.JRadioButton rbn_KeToan;
    private javax.swing.JTable tbl_TKNhanVien;
    private javax.swing.JTextField txt_MatKhau;
    private javax.swing.JTextField txt_TenDangNhap;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
